## Numpy
- designed for fast numerical cumputing
- widely used in science and engineering
- The numpy library contains multidimensional array data structures,such as the homogenous,N-dimensional ndarrays


### python list:-eg.,[1,2,3,4]
- flexible,slow,better for heterogenous array
### np arrays
- Numpy stores data in continuous memory blocks
- Uses less memory(optimized storage)
- built in mathematical functions
- homogenous,fast
- optimized in C
- better memory optimization compared to python list
- speed compared to python list
- Supports direct vectorized operations

### Importing numpy

In [2]:
import numpy as np

### Converting python list to numpy array

In [10]:
import numpy as np
arr= np.array([1,2,3,4])
print(arr,"\n",type(arr))

[1 2 3 4] 
 <class 'numpy.ndarray'>


#### Numpy arrays are faster(optimized in C)
#### Justification

In [24]:
import numpy as np
import time
#execution performance

size=10_000_000

#time taken by python list
py_list=list(range(size)) #[1,2,3,4,....]
start_time=time.time()
sq_time=[x**2 for x in py_list]
end_time=time.time()
print(f"python list time={end_time - start_time}second")

#time taken by numpy array
#vectorization-Vectorization in NumPy reduces the need 
#for explicit Python for loops, making numerical operations much faster.
np_array=np.array(py_list)
start_time=time.time()
sq_time=np_array**2
end_time=time.time()
print(f"numpy array time={end_time - start_time}second")

python list time=0.3183250427246094second
numpy array time=0.06716609001159668second


#### Numpy array uses less memory(optimized storage)
#### justification

In [30]:
import sys
print(f"python list size ={sys.getsizeof(py_list)*len(py_list)} bytes")
print(f"numpy array size ={np_array.nbytes} bytes")

python list size =800000560000000 bytes
numpy array size =80000000 bytes


### Why python list takes more memory ?
#### python list contain store additional meta data apart from actual data
### Why Numpy is faster?
- Homogenous data types and Contiguous memory
- Vector Operations & C implementations
- Reduced Overhead

### Creating Numpy array

#### using list

In [44]:
arr=np.array([1,2,3,4,5])
print(arr,type(arr),arr.dtype,arr.shape)
arr=np.array([1,2,3,4,5,"prime"])
print(arr,type(arr),arr.dtype,arr.shape)
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr2D,arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


#### using built-in method

In [87]:
array=np.zeros([2,])
print(array,array.shape)
print("\n")

arr=np.zeros([2,3],dtype="int64")#prefill
print(arr,arr.shape)
print("\n")

arr1=np.ones([3,4])#prefill
print(arr1,arr1.shape)
print("\n")

arr3=np.full([2,3],100)#prefill with value
print(arr3)
print("\n")

arr4=np.eye(3)#Identity matrix
print(arr4,arr4.shape)
print("\n")

arr5=np.arange(1,10)#range elements
arr6=np.arange(1,10,2)
print(arr5,arr5.shape)
print(arr6,arr6.shape)
print("\n")

arr7=np.linspace(1,100,4)##evenly spaced arrays
arr8=np.linspace(1,100,3)##evenly spaced arrays
arr9=np.linspace(1,100,4,dtype=int)##evenly spaced arrays
print(arr7)
print(arr8)
print(arr9)

[0. 0.] (2,)


[[0 0 0]
 [0 0 0]] (2, 3)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] (3, 4)


[[100 100 100]
 [100 100 100]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)


[1 2 3 4 5 6 7 8 9] (9,)
[1 3 5 7 9] (5,)


[  1.  34.  67. 100.]
[  1.   50.5 100. ]
[  1  34  67 100]


### Numpy array properties

In [106]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

print("Dimension:",arr.shape)# dimension=m x n
print("Size:",arr.size)# tot element
print("Type:",arr.dtype)
print("Number of Dimension:",arr.ndim)
float_type=arr.astype(np.float64)
print("Type:",float_type.dtype)


[[1 2 3]
 [4 5 6]]
Dimension: (2, 3)
Size: 6
Type: int64
Number of Dimension: 2
Type: float64


## Operations on NumPy Arrays

#### Reshaping

In [116]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped=arr.reshape([3,2])
print(reshaped,reshaped.shape)

flattened=arr.flatten()
print(flattened)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6]


#### Indexing

In [133]:
#normal Indexing
arr=np.array([1,2,3,4,5,6,7])
print(arr[0])

arr1=np.array([[1,2,3,4],[5,6,7,8]])
print(arr1[1][3])
print(arr1[1][1])
print(arr1[0][2])

#Fancy Indexing
idx=[0,2,5]
print(arr[idx])

#Boolean Indexing
print(arr[arr//3])
print(arr[arr>3])
print(arr[arr !=1])

1
8
6
3
[1 3 6]
[1 1 2 2 2 3 3]
[4 5 6 7]
[2 3 4 5 6 7]


#### Slicing

In [137]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:4])
print(arr[:4])
print(arr[4:])
print(arr[::-1])

[2 3 4]
[1 2 3 4]
[5 6 7]
[7 6 5 4 3 2 1]


### Difference between python list and numpy array in terms of slicing
- python list creates a copy of original list
- while numpy array gives a view of that original list neithen than creating seperately creating python list
## Justification

In [142]:
#Python List
nums=[1,2,3,4,5]
sub_arr=nums[1:3]
print(sub_arr)
sub_arr[0]=200
print(sub_arr)
print(nums)

#numpy array
arr=np.array([1,2,3,4,5])
sub_arr=arr[1:3]
print(sub_arr)
sub_arr[0]=200
print(sub_arr)
print(arr)

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]
[2 3]
[200   3]
[  1 200   3   4   5]


### Numpy data types
- Integer
    - int32,int64
- Floating point nums
    - float32,float64
- Boolean
    - bool
- Complex nums
    - complex32,complex64
- String
    - S(byte-str) & U(unicode-str)
- Object
    - generic python objects

## Axes in Multi-Dimensional Arrays

#### Axes=Dimension
- 1D= 1axis(axis 0)
- 2D= 2axes(axis 0 - row,axis 1- column)
- 3D= 3axes(axis 0 - row,axis 1 - column, axis 2 - channel or layer)
 - 3D array is the combination of multiple 2D array or matrix.
#### A grayscale image represents each pixel with a single intensity value, while a colored image represents each pixel using three color channels (RGB/BGR).
#### In terms of Matrix
#### The computer sees the pattern of 0s (black pixels) and recognizes the shape as 7.
#### Grayscale = 2D matrix (height × width), Color = 3D matrix (height × width × 3)
###

In [26]:
# Multidimensional Array
#2D arrays
arr2D=np.array([[1,2,3],[4,5,6,],[7,8,9]])
print(arr2D)
print(np.sum(arr2D))
sum_of_column=np.sum(arr2D,axis=0)
print(sum_of_column)
sum_of_rows=np.sum(arr2D,axis=1)
print(sum_of_rows)

#slicing
print(arr2D[0:2,1:2])

#3D arrays
"""
multiple 2D array with index 0 and 1 for the following arr3D
"""

arr3D=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]) #2 x 3 x 2
print(arr3D,arr3D.shape)

#indexing
print(arr3D[0,1,1])
print(arr3D[1,1,0])
#slicing
print(arr3D[:,0,:]) #first row from both layers
print(arr3D[:,:,0]) #first column from both layers
#manipulating elements
arr3D[:,0,:]=99
print(arr3D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
9
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


### Vectorization

In [34]:
#Vectorization
import numpy as np
arr=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(arr **2)
print(arr2 +2)
print(arr+arr2)

[ 1  4  9 16 25]
[ 8  9 10 11 12]
[ 7  9 11 13 15]


### Broadcasting

### Broadcasting-Scaling our array without using extra memory
### Broadcasting means NumPy can perform operations on arrays of different shapes by automatically expanding the smaller array to match the larger one.
### Broadcasting allows NumPy to perform operations between arrays of compatible different shapes without explicitly copying the smaller array.
### When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimension and works its way left. Two dimensions are compatible when

- they are equal, or

- one of them is 1.

- For example, if a.shape is (5,1), b.shape is (1,6), c.shape is (6,) and d.shape is () so that d is a scalar, then a, b, c, and d are all broadcastable to dimension (5,6); and

  - a acts like a (5,6) array where a[:,0] is broadcast to the other columns,
  - b acts like a (5,6) array where b[0,:] is broadcast to the other rows,
  - c acts like a (1,6) array and therefore like a (5,6) array where c[:] is broadcast to every row, and finally,
  - d acts like a (5,6) array where the single value is repeated.



In [40]:
# broadcasting
arr=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
arr2=np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr+arr2)
#The error shown is because of incompactability of the broadcasting rules

ValueError: operands could not be broadcast together with shapes (3,5) (2,5) 

### Use of Broadcasting
#### Vector Normalization
- Normalization an array means transforming its values so they fit into a specific scale or range
- Normalization is implement to increase the performance of ML algorithm
- Normalization works in such a way that the mean of transformed normalized array will always be 0 and std_deviation will be close to 1

In [47]:
#normalize
arr=np.array([[1,2],[3,4]])
mean=np.mean(arr)
std_deviation=np.std(arr)
normalized_array=(arr-mean)/std_deviation
print(normalized_array)
print(mean)
print(std_deviation)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


### Mathematical Function(Aggregate)

In [67]:
#MAthematical fnx
# Aggregation
arr=np.array([1,2,8,4,5])
print(np.sum(arr))
print(np.prod(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.std(arr))
print(np.var(arr))

#Power
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,2))

#Extras
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))

20
320
4.0
4.0
0
2
2.449489742783178
6.0
[ 1  4 64 16 25]
[1.         1.41421356 2.82842712 2.         2.23606798]
[ 1  4 64 16 25]
[1 2 4 5 8]
[1 2 4 5 8]
[1 2 8 4 5]
